version: '3.8'

networks:
    default:
        driver: bridge

services:
    nginx:
        container_name: club-manager-api-nginx
        build: 
            context: ./docker/nginx
            dockerfile: Dockerfile
        # restart: always 
        networks:
            - default
        ports:
            - "8001:80"
        depends_on: 
            - php
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        container_name: club-manager-api-php
        build: 
            context: ./docker/php
            dockerfile: Dockerfile
        # restart: always 
        volumes:
            - .:/var/www/html
        ports:
            - "9000"
        # depends_on: 
        #     - postgres
        networks:
            - default

    # postgres:
    #     container_name: club-manager-db
    #     image: postgres:12.0-alpine
    #     # restart: always
    #     ports:
    #         - "4000:5432"
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: pass123
    #         POSTGRES_DB: club-manager
    #     networks:
    #         - default
    #     # volumes:  
    #     #     - “./docker/dbdata:/var/lib/postgresql/data”
            
